---

version: '3'
services: 

  # ==> Kafka Section
  # =================
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks: 
      - kafka
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    networks: 
      - kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "fluentd:1:1"          # 6 partitions, 2/3 nodes to run
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    networks: 
      - kafka
    ports:
      - 9093:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2

  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    networks: 
      - kafka
    ports:
      - 9094:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3

  burrow:
    image: docker.pkg.github.com/linkedin/burrow/burrow:v1.3.4
    container_name: burrow
    volumes:
      - ./burrow/burrow.toml:/etc/burrow/burrow.toml
      - burrow_tmp:/var/tmp/burrow
    ports:
      - 8000:8000
    depends_on:
      - zookeeper
      - kafka1
    networks: 
      - kafka

  # ==> Elastic Stack section
  # =========================
  elastic1: 
    image: elasticsearch:7.9.1
    container_name: elastic1
    environment:
      - node.name=elastic1
      - cluster.name=stretchy-cluster
      - discovery.seed_hosts=elastic1
      - cluster.initial_master_nodes=elastic1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=America/Toronto"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic1_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: kibana:7.9.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elastic1:9200
      TZ: America/Toronto
    ports: 
      - 5601:5601
    depends_on:
      - elastic1
    networks:
      - elastic

  # ==> Fluentd section
  # ==================
  fluentd: 
    build: ./fluentd 
    container_name: fluentd
    volumes: 
      - ./fluentd/fluentd.conf:/fluentd/fluentd.conf:ro
      - ./fluentd/keys/:/fluentd/keys/:ro
      - fluentd_buffer:/fluentd/buffer/:rw
    environment: 
      - "TZ=America/Toronto"
    ports: 
      - 5514:5514/udp
      - 24224:24224
      - 25225:25225
    depends_on:
      - elastic1
    networks:
      - elastic
      - influxdb
      - kafka

  # ==> Influx & Grafana section
  # ============================
  influxdb: 
    image: quay.io/influxdb/influxdb:2.0.0-beta
    container_name: influxdb
    volumes: 
      - influxdb_data:/var/lib/influxdb
    ports: 
      - 9999:9999
    networks: 
      - influxdb

  grafana: 
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes: 
      - grafana_data:/var/lib/grafana
    ports: 
      - 3000:3000
    networks: 
      - elastic
      - influxdb

networks: 
  elastic: 
  influxdb: 
  kafka: 
 
volumes: 
  elastic1_data: 
  zk_data: 
  zk_logs:
  kafka_data: 
  influxdb_data:
  grafana_data: 
  fluentd_buffer:
  burrow_tmp: 
  
