---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  labels:
   app: fluentd
spec:
  type: NodePort
  ports:
  - name: forward
    protocol: TCP
    port: 5000
    nodePort: 32100
  - name: forward-udp
    protocol: UDP
    port: 5000
    nodePort: 32100
  selector:
    app: fluentd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: localhost:32000/nbailey/fluentd:latest
        ports:
        - name: forward
          containerPort: 5000
          protocol: TCP
        - name: forward-udp
          containerPort: 5000
          protocol: UDP
        livenessProbe:
          tcpSocket:
            port: forward
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
        - name: KAFKA_BROKER
          value: "kafka-service.default.svc.cluster.local"
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch.default.svc.cluster.local"
        - name: INFLUXDB_HOST
          value: "http://influxdb.default.svc.cluster.local:8086"
        - name: INFLUXDB_TOKEN
          value: "UIKGpftbcLBWYMYzApGDNqCWGDamZOWACLLwAClCrbriKvG8HIGARI_SKu0BT1F8zFHNFd60LuFzzYZGoUk9Yg=="
