---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  labels:
   service: fluentd
spec:
  ports:
  - port: 24224
    name: forward
  selector:
    service: fluentd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: localhost:32000/nbailey/fluentd:latest
        ports:
        - name: forward
          containerPort: 24224
        env:
        - name: KAFKA_BROKER
          value: "kafka-service.default.svc.cluster.local"
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch.default.svc.cluster.local"
        - name: INFLUXDB_HOST
          value: "http://influxdb.default.svc.cluster.local:8086"
        - name: INFLUXDB_TOKEN
          value: "kEVV5LEniZv49EM2jS_RlPbFL7pCPsqFfI3cOHKhVIC3rnjVPwNhK9rgafNCEJaRU___Ap7TUGS5L--ZozNxxQ=="
