---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper
    service: kafka-broker
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper-service
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper-0
        image: wurstmeister/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['spec.pod.beta.kubernetes.io/statefulset-index']
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-0.zookeeper-service.default.svc.cluster.local
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-1.zookeeper-service.default.svc.cluster.local
        - name: ZOOKEEPER_SERVER_3
          value: zookeeper-2.zookeeper-service.default.svc.cluster.local
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        resources: 
          limits: 
            cpu: "500m"
            memory: "300Mi"
          requests: 
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - zookeeper
              topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 10Gi
