---

version: '3'
services: 

  elastic1: 
    image: elasticsearch:7.9.1
    container_name: elastic1
    environment:
      - node.name=elastic1
      - cluster.name=stretchy-cluster
      - discovery.seed_hosts=elastic1
      - cluster.initial_master_nodes=elastic1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=America/Toronto"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic1_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic


  kibana:
    image: kibana:7.9.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elastic1:9200
      TZ: America/Toronto
    ports: 
      - 5601:5601
    depends_on:
      - elastic1
    networks:
      - elastic

  fluentd: 
    build: ./fluentd 
    container_name: fluentd
    volumes: 
      - ./fluentd/fluentd.conf:/fluentd/fluentd.conf:ro
    environment: 
      - "TZ=America/Toronto"
    ports: 
      - 5514:5514/udp
      - 24224:24224
    depends_on:
      - elastic1
    networks:
      - elastic
      - influxdb

  influxdb: 
    image: quay.io/influxdb/influxdb:2.0.0-beta
    container_name: influxdb
    volumes: 
      - influxdb_data:/var/lib/influxdb
    ports: 
      - 9999:9999
    networks: 
      - influxdb

  grafana: 
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes: 
      - grafana_data:/var/lib/grafana
    ports: 
      - 3000:3000
    networks: 
      - elastic
      - influxdb

networks: 
  elastic: 
  influxdb: 
 
volumes: 
  elastic1_data: 
  influxdb_data:
  grafana_data: 
