---

version: '3'
services: 

  elastic1: 
    image: elasticsearch:7.9.1
    container_name: elastic1
    environment:
      - node.name=elastic1
      - cluster.name=stretchy-cluster
      - discovery.seed_hosts=elastic2,elastic3
      - cluster.initial_master_nodes=elastic1,elastic2,elastic3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "TZ=America/Toronto"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic1_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  elastic2: 
    image: elasticsearch:7.9.1
    container_name: elastic2
    environment:
      - node.name=elastic2
      - cluster.name=stretchy-cluster
      - discovery.seed_hosts=elastic1,elastic3
      - cluster.initial_master_nodes=elastic1,elastic2,elastic3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "TZ=America/Toronto"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic2_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  elastic3: 
    image: elasticsearch:7.9.1
    container_name: elastic3
    environment:
      - node.name=elastic3
      - cluster.name=stretchy-cluster
      - discovery.seed_hosts=elastic1,elastic2
      - cluster.initial_master_nodes=elastic1,elastic2,elastic3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "TZ=America/Toronto"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic3_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: kibana:7.9.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elastic1:9200
      TZ: America/Toronto
    ports: 
      - 5601:5601
    depends_on:
      - elastic1
      - elastic2
      - elastic3
    networks:
      - elastic

  fluentd: 
    build: ./fluentd 
    container_name: fluentd
    volumes: 
      - ./fluentd/fluentd.conf:/fluentd/fluentd.conf:ro
    environment: 
      - "TZ=America/Toronto"
    ports: 
      - 5514:5514/udp
      - 8888:8888
      - 24224:24224
    depends_on:
      - elastic1
      - elastic2
      - elastic3
    networks:
      - elastic


networks: 
  elastic: 

volumes: 
  elastic1_data: 
  elastic2_data: 
  elastic3_data: 
